### ISSUE TITLE
Editor glitches

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#4664] opened 2024-02-16 08:45 UTC

**Comment by aonnikov** [comment] 2024-02-16 09:05
@haiodo please provide more details 😄

**Comment by haiodo** [comment] 2024-02-16 09:54
details

**Comment by haiodo** [comment] 2024-02-16 09:54
details

**Comment by aonnikov** [comment] 2024-02-20 05:31
Duplicate of an issue with triggering description change on blur

**Closed as completed** 2024-02-20 09:47 UTC
