### ISSUE TITLE
Table display breaks after some updates

### ISSUE THREAD

**Issue by lexiv0re** [hcengineering/platform#4463] opened 2024-01-27 08:33 UTC
**Summary**

Intermittent issue! May be hard to reproduce. But seen several times on different tables.

**Steps to reproduce:**

1. Go to products table (qms) where 1 product already exists
2. Create a new product

Note: similar issue also been seen in tables in the contacts app.

**Actual Result**

The existed product is not displayed anymore - only the row frame.

![](https://front.hc.engineering/files/bb793ec1-252e-4419-8998-7f220ababdfa/87007c69-2fed-4cce-b72a-90b552ab2787&width=1738)

**Expected Result**

Both products are displayed in the table correctly

Note: refresh fixes the issue

**Comment by haiodo** [comment] 2024-01-28 08:10
[Zinovyev Alexey](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63fefffb6e876eaf328df878&label=Zinovyev%20Alexey)did you check for browser console for any errors?

**Comment by lexiv0re** [comment] 2024-01-29 02:45
I cannot remember for sure. Either I forgot to check or there were no errors in the console.

**Comment by aonnikov** [comment] 2024-01-29 03:43
I’ve just managed to reproduce the issue. There are no errors in the browser console. 
The problem is related to lazy loading, when we add a new row and row index is higher or equal current rows limit, then the row is rendered, but cells in the row are not.

The best way to reproduce is to start from empty table, add first item, and then add second item. After this the table breaks.

**Comment by aonnikov** [comment] 2024-02-20 10:07
fixed in <https://github.com/hcengineering/platform/pull/4486>

**Closed as completed** 2024-02-20 10:06 UTC
