### ISSUE TITLE
Cannot archive items in inbox

### ISSUE THREAD

**Issue by ThetaDR** [hcengineering/platform#5084] opened 2024-03-28 07:44 UTC
![](https://front.hc.engineering/files?workspace=platform&file=129f2581-e101-40d7-8655-9cc14e52847e&width=792)

`deleteContextNotifications`

```
[
    {
        "_id": "66052e730c758fc0cc029bb2",
        "_class": "core:class:TxRemoveDoc",
        "space": "core:space:Tx",
        "modifiedBy": "63bbaa5093f7b75720ef0f11",
        "modifiedOn": 1711615603753,
        "objectId": "660503136c55e9a9157f0f64",
        "objectClass": "notification:class:ActivityInboxNotification",
        "objectSpace": "650d7e3b667f87b0690e5e81"
    },
    {
        "_id": "66052e730c758fc0cc029bb3",
        "_class": "core:class:TxRemoveDoc",
        "space": "core:space:Tx",
        "modifiedBy": "63bbaa5093f7b75720ef0f11",
        "modifiedOn": 1711615603753,
        "objectId": "660503146c55e9a9157f0f9a",
        "objectClass": "notification:class:CommonInboxNotification",
        "objectSpace": "650d7e3b667f87b0690e5e81"
    },
    {
        "_id": "66052e730c758fc0cc029bb4",
        "_class": "core:class:TxRemoveDoc",
        "space": "core:space:Tx",
        "modifiedBy": "63bbaa5093f7b75720ef0f11",
        "modifiedOn": 1711615603753,
        "objectId": "660509b16c55e9a9157f2a36",
        "objectClass": "notification:class:ActivityInboxNotification",
        "objectSpace": "650d7e3b667f87b0690e5e81"
    },
    {
        "_id": "66052e730c758fc0cc029bb5",
        "_class": "core:class:TxUpdateDoc",
        "space": "core:space:Tx",
        "modifiedBy": "63bbaa5093f7b75720ef0f11",
        "modifiedOn": 1711615603753,
        "objectId": "660503136c55e9a9157f0f62",
        "objectClass": "notification:class:DocNotifyContext",
        "objectSpace": "650d7e3b667f87b0690e5e81",
        "operations": {
            "lastViewedTimestamp": 1711615603753
        }
    }
]
```

![](https://front.hc.engineering/files?workspace=platform&file=129f2581-e101-40d7-8655-9cc14e52847e&width=792)

`deleteContextNotifications`

```
[
    {
        "_id": "66052e730c758fc0cc029bb2",
        "_class": "core:class:TxRemoveDoc",
        "space": "core:space:Tx",
        "modifiedBy": "63bbaa5093f7b75720ef0f11",
        "modifiedOn": 1711615603753,
        "objectId": "660503136c55e9a9157f0f64",
        "objectClass": "notification:class:ActivityInboxNotification",
        "objectSpace": "650d7e3b667f87b0690e5e81"
    },
    {
        "_id": "66052e730c758fc0cc029bb3",
        "_class": "core:class:TxRemoveDoc",
        "space": "core:space:Tx",
        "modifiedBy": "63bbaa5093f7b75720ef0f11",
        "modifiedOn": 1711615603753,
        "objectId": "660503146c55e9a9157f0f9a",
        "objectClass": "notification:class:CommonInboxNotification",
        "objectSpace": "650d7e3b667f87b0690e5e81"
    },
    {
        "_id": "66052e730c758fc0cc029bb4",
        "_class": "core:class:TxRemoveDoc",
        "space": "core:space:Tx",
        "modifiedBy": "63bbaa5093f7b75720ef0f11",
        "modifiedOn": 1711615603753,
        "objectId": "660509b16c55e9a9157f2a36",
        "objectClass": "notification:class:ActivityInboxNotification",
        "objectSpace": "650d7e3b667f87b0690e5e81"
    },
    {
        "_id": "66052e730c758fc0cc029bb5",
        "_class": "core:class:TxUpdateDoc",
        "space": "core:space:Tx",
        "modifiedBy": "63bbaa5093f7b75720ef0f11",
        "modifiedOn": 1711615603753,
        "objectId": "660503136c55e9a9157f0f62",
        "objectClass": "notification:class:DocNotifyContext",
        "objectSpace": "650d7e3b667f87b0690e5e81",
        "operations": {
            "lastViewedTimestamp": 1711615603753
        }
    }
]
```

**Comment by BykhovDenis** [comment] 2024-03-28 15:23
[Alexey Zinovyev](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63fefffb6e876eaf328df878&label=Alexey%20Zinovyev) I think it’s fixed and can be closed?

**Comment by lexiv0re** [comment] 2024-03-28 15:26
[Denis Bykhov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d983ba125a3831a3424ff&label=Denis%20Bykhov) It must be fixed but I still wanna investigate the objects from the transactions log to see why Inbox deletes something from the project’s space.

**Comment by lexiv0re** [comment] 2024-04-14 09:57
[Kristina Fefelova](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63204fc031b9728f9e6b2e1a&label=Kristina%20Fefelova)is it expected and by design that all these notification-related items live in the tracker project space? `650d7e3b667f87b0690e5e81` - is the tracker project space. Are all the notifications added to the object’s space?

**Comment by kristina-fefelova** [comment] 2024-04-15 11:59
No, I think I need to move notifications to public space (`notification.space.Notification` or something like)

**Comment by BykhovDenis** [comment] 2024-04-15 15:45
I think notifications should be in related object spaces (for it disappear when we have not access). @haiodo what do you think?

**Comment by lexiv0re** [comment] 2024-06-13 09:26
I think it will be re-visited during the spaces concept overhaul being done by [Denis Bykhov](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d983ba125a3831a3424ff&label=Denis%20Bykhov) so closing this one.

**Closed as completed** 2024-08-07 08:35 UTC
